### ISSUE TITLE
when i try to login !!

### ISSUE THREAD

**Issue by alhajymoayed** [arashactive/laramint#2]
![image](https://user-images.githubusercontent.com/49277634/180108112-f42fa0b1-e2e8-405f-be77-9710d8bca486.png)

**Comment by arashactive** [comment]
As the first thing: 
php artisan migrate:fresh --seed, 
if doesn't work for your, please let me know which user logged in last?

**Comment by alhajymoayed** [comment]
i write :
php artisan migrate:fresh --seed 
But the problem is still
Logged in as super admin

**Comment by arashactive** [comment]
I will solve this problem in the next commit. Thanks for your feedback

**Comment by arashactive** [comment]
Hello again, please check your badge tables on your database, maybe your badge tables are empty. in administrator, you can create some new badges to solve your problem.
