### ISSUE TITLE
Departments Issue

### ISSUE THREAD

**Issue by MaheKarim** [arashactive/laramint#7]
**Describe the bug**
Department Showing Error

**To Reproduce**
Go Frontend as a Fresh Install

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Emmanuel-Odero** [comment]
@MaheKarim I am unable to fully grasp your issue please elaborate more;
What is the issue you facing when you visit the website.
